site_name: Wireless Communication Docs
site_url: https://boyin8.github.io/wireless-docs
site_author: Bo Yin
site_description: This is technical docs site for wireless communication.
repo_name: boyin8/wireless-docs
repo_url: https://github.com/boyin8/wireless-docs

copyright: Copyright &copy; 2024 ~ now | Bo Yin

nav:
  - Home: index.md
  - Baseband Signal Model: baseband_signal.md
  - Wireless Channel Models: channel_models.md
  - Channel Estimation: channel_estimation.md
  - OFDM: ofdm.md
  - Channel Capacity: channel_capacity.md
  - Beamforming: beamforming.md

theme:
  name: material
  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
    - toc.integrate
    - toc.follow
    - navigation.path
    - navigation.top
    - navigation.tabs
    - navigation.prune
    - navigation.footer
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - navigation.indexes
    - search.share
    - search.suggest

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
